"""
SoverGrid CLI
Main command-line interface entry point using Click.

This is Project 2: The Mock Orchestrator.
Registers all terminal commands: deploy, init, status.
"""

import asyncio
import json
import os
import shutil
from pathlib import Path

import click
import httpx

from sovergrid import __version__, __app_name__
from sovergrid.logger import get_logger, Colors
from sovergrid.config import SoverGridConfig, CONFIG_FILENAME
from sovergrid.orchestrator import run_deployment
from sovergrid.dockerizer import generate_dockerfile, detect_project_type
from sovergrid.services.compute import ComputeService
from sovergrid.services.storage import StorageService
from sovergrid.services.ml_training import MLTrainingService
from sovergrid.services.database import DatabaseService
from sovergrid.services.cdn import CDNService
from sovergrid.services.blockchain import BlockchainService

log = get_logger(__name__)

CREDENTIALS_DIR = Path.home() / ".sovergrid"
CREDENTIALS_FILE = CREDENTIALS_DIR / "credentials.json"
DEFAULT_API_URL = "https://web-production-4966c.up.railway.app"


# Default sovergrid.yaml content for `sovergrid init`
DEFAULT_CONFIG = """\
# SoverGrid Configuration
# Generated by 'sovergrid init'
# Docs: https://github.com/sovergrid/sovergrid-cli

app:
  name: "{app_name}"
  description: "My decentralized application"

compute:
  provider: "akash"
  region: "us-west"
  resources:
    cpu: 1
    memory: "512Mi"
    storage: "1Gi"

# Eco-Friendly Routing
# Set to 'true' to only use renewable energy compute providers
green: false

storage:
  provider: "filecoin"
  pin: true

build:
  dockerfile: "Dockerfile"
  port: 8080

payment:
  token: "USDC"
  max_budget: 5.00
"""


@click.group()
@click.version_option(version=__version__, prog_name=__app_name__)
def cli():
    """
    SoverGrid: The one-click, un-censorable decentralized AWS.

    Deploy your applications to decentralized networks (Akash, Filecoin)
    with a single command. No rewriting code. No centralized gatekeepers.
    """
    pass


@cli.command()
@click.option(
    "--config", "-c",
    default=None,
    help="Path to sovergrid.yaml (defaults to current directory).",
)
def deploy(config):
    """Deploy your application to the decentralized network."""
    log.info(
        f"{Colors.BOLD}SoverGrid CLI v{__version__}{Colors.RESET}"
    )
    log.info("Initializing deployment pipeline...\n")

    # Load and validate config
    cfg = SoverGridConfig.load(config)

    # Run the async deployment pipeline
    result = asyncio.run(run_deployment(cfg))

    if result.get("compute"):
        log.info(
            f"\n  {Colors.BOLD}Your app is live at:{Colors.RESET} "
            f"{Colors.CYAN}{result['compute'].get('endpoint', 'N/A')}{Colors.RESET}\n"
        )


@cli.command()
@click.option(
    "--port", "-p",
    default=8080,
    help="Port your application listens on (default: 8080).",
)
def init(port):
    """Initialize a new SoverGrid project in the current directory."""
    cwd = os.getcwd()
    project_name = os.path.basename(cwd)

    log.info(
        f"{Colors.BOLD}SoverGrid CLI v{__version__}{Colors.RESET}"
    )
    log.info(f"Initializing project '{project_name}'...\n")

    # Step 1: Generate sovergrid.yaml
    config_path = os.path.join(cwd, CONFIG_FILENAME)

    if os.path.exists(config_path):
        log.warning(
            f"{CONFIG_FILENAME} already exists. Skipping config generation."
        )
    else:
        config_content = DEFAULT_CONFIG.format(app_name=project_name)
        with open(config_path, "w") as f:
            f.write(config_content)
        log.info(
            f"{Colors.GREEN}Created {CONFIG_FILENAME}{Colors.RESET}"
        )

    # Step 2: Auto-detect project and generate Dockerfile
    project_type = detect_project_type(cwd)
    if project_type:
        generate_dockerfile(cwd, port=port)
    else:
        log.info(
            "No requirements.txt or package.json found.\n"
            "  A Dockerfile will be generated when you add one\n"
            "  and run 'sovergrid init' again."
        )

    # Step 3: Summary
    log.info(
        f"\n  {Colors.BOLD}{Colors.GREEN}"
        f"  Project initialized successfully.{Colors.RESET}\n\n"
        f"  Next steps:\n"
        f"  1. Review your {CONFIG_FILENAME}\n"
        f"  2. Run {Colors.CYAN}sovergrid deploy{Colors.RESET} "
        f"to deploy\n"
    )


@cli.command()
def status():
    """Check the status of your current deployment (mock)."""
    log.info(
        f"{Colors.BOLD}SoverGrid CLI v{__version__}{Colors.RESET}"
    )

    # In the real implementation, this will query the Akash API
    # for the status of the user's active deployments.
    log.info("Checking deployment status...\n")

    # Mock response
    log.info(
        f"  {Colors.GREEN}Status: ACTIVE{Colors.RESET}\n"
        f"  Provider: Akash Network\n"
        f"  Uptime: 99.97%\n"
        f"  Endpoint: https://akash-mock-123456.akash.network\n"
        f"  Monthly Cost: $0.62 (USDC)\n"
    )


@cli.command()
def info():
    """Display information about SoverGrid and the current config."""
    log.info(
        f"\n"
        f"  {Colors.BOLD}{Colors.MAGENTA}SoverGrid{Colors.RESET} "
        f"v{__version__}\n"
        f"  The one-click, un-censorable decentralized AWS.\n\n"
        f"  Supported Compute:  Akash, Spheron, Golem\n"
        f"  Supported Storage:  Filecoin, Arweave, IPFS\n"
        f"  Payment Tokens:     USDC, SVR\n"
        f"  License:            MIT\n"
    )

    # Try to load config if it exists
    config_path = os.path.join(os.getcwd(), CONFIG_FILENAME)
    if os.path.exists(config_path):
        cfg = SoverGridConfig.load(config_path)
        log.info(f"  Current project config:{cfg.summary()}")
    else:
        log.info(
            f"  No {CONFIG_FILENAME} in current directory.\n"
            f"  Run {Colors.CYAN}sovergrid init{Colors.RESET} to get started.\n"
        )


@cli.command()
@click.option("--email", prompt="Email", help="Your email address.")
@click.option("--password", prompt=True, hide_input=True, confirmation_prompt=True, help="Choose a password (min 8 chars).")
def register(email, password):
    """Create a new SoverGrid developer account."""
    log.info(f"{Colors.BOLD}SoverGrid CLI v{__version__}{Colors.RESET}")
    log.info("Creating your account...\n")

    api_url = os.environ.get("SOVERGRID_API_URL", DEFAULT_API_URL)

    try:
        response = httpx.post(
            f"{api_url}/auth/register",
            json={"email": email, "password": password},
            timeout=15.0,
        )

        if response.status_code == 409:
            log.error("An account with this email already exists. Use 'sovergrid login' instead.")
            return
        if response.status_code == 400:
            log.error(response.json().get("detail", "Invalid input."))
            return

        response.raise_for_status()
        data = response.json()

        # Save credentials
        CREDENTIALS_DIR.mkdir(parents=True, exist_ok=True)
        with open(CREDENTIALS_FILE, "w") as f:
            json.dump({"access_token": data["access_token"], "email": data["email"]}, f, indent=2)

        log.info(
            f"  {Colors.GREEN}Account created successfully.{Colors.RESET}\n"
            f"  Email: {data['email']}\n"
            f"  Token saved to: {CREDENTIALS_FILE}\n\n"
            f"  Run {Colors.CYAN}sovergrid deploy{Colors.RESET} to get started.\n"
        )

    except httpx.ConnectError:
        log.error("Could not connect to the SoverGrid backend. Is it running?")
    except Exception as e:
        log.error(f"Registration failed: {str(e)}")


@cli.command()
@click.option("--email", prompt="Email", help="Your email address.")
@click.option("--password", prompt=True, hide_input=True, help="Your password.")
def login(email, password):
    """Log in to your SoverGrid account."""
    log.info(f"{Colors.BOLD}SoverGrid CLI v{__version__}{Colors.RESET}")
    log.info("Authenticating...\n")

    api_url = os.environ.get("SOVERGRID_API_URL", DEFAULT_API_URL)

    try:
        response = httpx.post(
            f"{api_url}/auth/login",
            json={"email": email, "password": password},
            timeout=15.0,
        )

        if response.status_code == 401:
            log.error("Invalid email or password.")
            return

        response.raise_for_status()
        data = response.json()

        # Save credentials
        CREDENTIALS_DIR.mkdir(parents=True, exist_ok=True)
        with open(CREDENTIALS_FILE, "w") as f:
            json.dump({"access_token": data["access_token"], "email": data["email"]}, f, indent=2)

        log.info(
            f"  {Colors.GREEN}Logged in successfully.{Colors.RESET}\n"
            f"  Email: {data['email']}\n"
            f"  Token saved to: {CREDENTIALS_FILE}\n"
        )

    except httpx.ConnectError:
        log.error("Could not connect to the SoverGrid backend. Is it running?")
    except Exception as e:
        log.error(f"Login failed: {str(e)}")


@cli.command()
def logout():
    """Log out and remove saved credentials."""
    if CREDENTIALS_FILE.exists():
        CREDENTIALS_FILE.unlink()
        log.info(f"{Colors.GREEN}Logged out. Credentials removed.{Colors.RESET}")
    else:
        log.info("No credentials found. Already logged out.")


@cli.command()
@click.argument("address", required=False)
def balance(address: str = None):
    """
    Check the $SVR token balance for a specific wallet address.
    If no address is provided, defaults to the private key in .env.
    """
    log.info(f"{Colors.BLUE}Connecting to Sepolia blockchain...{Colors.RESET}")
    
    # Initialize the Blockchain service
    blockchain = BlockchainService()
    
    if not blockchain.is_connected:
        log.error(f"{Colors.RED}Failed to connect to the Ethereum network. Check your internet or RPC.{Colors.RESET}")
        return
        
    target_wallet = address or blockchain.wallet_address
    if not target_wallet:
        log.error(f"{Colors.RED}No wallet address provided and no PRIVATE_KEY found in .env.{Colors.RESET}")
        return
        
    log.info(f"Querying $SVR balance for wallet: {target_wallet}")
    
    balance = blockchain.get_token_balance(target_wallet)
    
    if balance is not None:
        log.info(f"{Colors.GREEN}===================================={Colors.RESET}")
        log.info(f"{Colors.GREEN}💰 BALANCE: {balance:,.2f} $SVR{Colors.RESET}")
        log.info(f"{Colors.GREEN}===================================={Colors.RESET}")
    else:
        log.error("Could not retrieve token balance. Have you set CONTRACT_ADDRESS in .env?")


# ─── Helper: Load a single service section from sovergrid.yaml ───

def _load_service_config(service_key: str, config_path: str = None) -> tuple:
    """
    Loads ONLY the relevant section from sovergrid.yaml for a single service.

    For example, if service_key is 'ml', this returns the contents of:
        ml:
          provider: "bittensor"
          model: "llama-3"
          ...

    Returns (service_config_dict, max_budget).
    """
    import yaml

    if config_path is None:
        config_path = os.path.join(os.getcwd(), CONFIG_FILENAME)

    if not os.path.exists(config_path):
        log.error(
            f"No {CONFIG_FILENAME} found.\n"
            f"  Run 'sovergrid init' first, then add a '{service_key}:' "
            f"section to your config."
        )
        return None, 0

    with open(config_path, "r") as f:
        raw = yaml.safe_load(f)

    if not isinstance(raw, dict):
        log.error(f"{CONFIG_FILENAME} is empty or invalid.")
        return None, 0

    service_config = raw.get(service_key)
    if service_config is None:
        log.error(
            f"No '{service_key}:' section found in your {CONFIG_FILENAME}.\n"
            f"  Add a '{service_key}:' block to use this service standalone."
        )
        return None, 0

    # Budget comes from the service block first, then payment block, then default
    max_budget = service_config.get(
        "budget",
        raw.get("payment", {}).get("max_budget", 5.00)
    )

    return service_config, float(max_budget)


# ─── Standalone Service Commands ─────────────────────────────────

@cli.command()
@click.option(
    "--config", "-c", default=None,
    help="Path to sovergrid.yaml.",
)
def train(config):
    """Train an AI model on decentralized GPUs (standalone)."""
    log.info(f"{Colors.BOLD}SoverGrid CLI v{__version__}{Colors.RESET}")
    log.info("Starting ML Training service...\n")

    service_config, max_budget = _load_service_config("ml", config)
    if service_config is None:
        return

    service = MLTrainingService(config=service_config, max_budget=max_budget)
    result = asyncio.run(service.run())

    if result and result.status != "failed":
        log.info(
            f"\n  {Colors.BOLD}Training complete:{Colors.RESET}\n"
            f"  Job:    {result.metadata.get('job_id', 'N/A')}\n"
            f"  Model:  {result.metadata.get('model', 'N/A')}\n"
            f"  GPUs:   {result.metadata.get('gpu_count', 'N/A')}x "
            f"{result.metadata.get('gpu_type', 'N/A')}\n"
            f"  Loss:   {result.metadata.get('final_loss', 'N/A')}\n"
            f"  Cost:   ${result.cost_usd:.4f}\n"
            f"  URL:    {Colors.CYAN}{result.endpoint}{Colors.RESET}\n"
        )


@cli.command()
@click.option(
    "--config", "-c", default=None,
    help="Path to sovergrid.yaml.",
)
def store(config):
    """Pin files to decentralized storage (standalone)."""
    log.info(f"{Colors.BOLD}SoverGrid CLI v{__version__}{Colors.RESET}")
    log.info("Starting Storage service...\n")

    service_config, max_budget = _load_service_config("storage", config)
    if service_config is None:
        return

    service = StorageService(config=service_config, max_budget=max_budget)
    result = asyncio.run(service.run())

    if result and result.status != "failed":
        log.info(
            f"\n  {Colors.BOLD}Pinning complete:{Colors.RESET}\n"
            f"  CID:      {result.metadata.get('cid', 'N/A')[:30]}...\n"
            f"  Provider: {result.provider}\n"
            f"  Cost:     ${result.cost_usd:.4f}\n"
            f"  Gateway:  {Colors.CYAN}{result.endpoint}{Colors.RESET}\n"
        )


@cli.command()
@click.option(
    "--config", "-c", default=None,
    help="Path to sovergrid.yaml.",
)
def db(config):
    """Provision a decentralized database (standalone)."""
    log.info(f"{Colors.BOLD}SoverGrid CLI v{__version__}{Colors.RESET}")
    log.info("Starting Database service...\n")

    service_config, max_budget = _load_service_config("database", config)
    if service_config is None:
        return

    service = DatabaseService(config=service_config, max_budget=max_budget)
    result = asyncio.run(service.run())

    if result and result.status != "failed":
        log.info(
            f"\n  {Colors.BOLD}Database ready:{Colors.RESET}\n"
            f"  Name:       {result.metadata.get('db_name', 'N/A')}\n"
            f"  Type:       {result.metadata.get('db_type', 'N/A')}\n"
            f"  Provider:   {result.provider}\n"
            f"  Cost:       ${result.cost_usd:.4f}/mo\n"
            f"  Connection: {Colors.CYAN}"
            f"{result.metadata.get('connection_string', 'N/A')}"
            f"{Colors.RESET}\n"
        )


@cli.command()
@click.option(
    "--config", "-c", default=None,
    help="Path to sovergrid.yaml.",
)
def cdn(config):
    """Push content to a decentralized CDN (standalone)."""
    log.info(f"{Colors.BOLD}SoverGrid CLI v{__version__}{Colors.RESET}")
    log.info("Starting CDN service...\n")

    service_config, max_budget = _load_service_config("cdn", config)
    if service_config is None:
        return

    service = CDNService(config=service_config, max_budget=max_budget)
    result = asyncio.run(service.run())

    if result and result.status != "failed":
        log.info(
            f"\n  {Colors.BOLD}CDN deployed:{Colors.RESET}\n"
            f"  Provider:    {result.provider}\n"
            f"  Edge Nodes:  {result.metadata.get('edge_nodes', 'N/A')}\n"
            f"  Cost:        ${result.cost_usd:.4f}\n"
            f"  URL:         {Colors.CYAN}{result.endpoint}{Colors.RESET}\n"
        )


def main():
    """Entry point for the console script."""
    cli()


if __name__ == "__main__":
    main()
