"""
SoverGrid CLI
Main command-line interface entry point using Click.

This is Project 2: The Mock Orchestrator.
Registers all terminal commands: deploy, init, status.
"""

import asyncio
import os
import shutil

import click

from sovergrid import __version__, __app_name__
from sovergrid.logger import get_logger, Colors
from sovergrid.config import SoverGridConfig, CONFIG_FILENAME
from sovergrid.orchestrator import run_deployment
from sovergrid.dockerizer import generate_dockerfile, detect_project_type

log = get_logger(__name__)


# Default sovergrid.yaml content for `sovergrid init`
DEFAULT_CONFIG = """\
# SoverGrid Configuration
# Generated by 'sovergrid init'
# Docs: https://github.com/sovergrid/sovergrid-cli

app:
  name: "{app_name}"
  description: "My decentralized application"

compute:
  provider: "akash"
  region: "us-west"
  resources:
    cpu: 1
    memory: "512Mi"
    storage: "1Gi"

storage:
  provider: "filecoin"
  pin: true

build:
  dockerfile: "Dockerfile"
  port: 8080

payment:
  token: "USDC"
  max_budget: 5.00
"""


@click.group()
@click.version_option(version=__version__, prog_name=__app_name__)
def cli():
    """
    SoverGrid: The one-click, un-censorable decentralized AWS.

    Deploy your applications to decentralized networks (Akash, Filecoin)
    with a single command. No rewriting code. No centralized gatekeepers.
    """
    pass


@cli.command()
@click.option(
    "--config", "-c",
    default=None,
    help="Path to sovergrid.yaml (defaults to current directory).",
)
def deploy(config):
    """Deploy your application to the decentralized network."""
    log.info(
        f"{Colors.BOLD}SoverGrid CLI v{__version__}{Colors.RESET}"
    )
    log.info("Initializing deployment pipeline...\n")

    # Load and validate config
    cfg = SoverGridConfig.load(config)

    # Run the async deployment pipeline
    result = asyncio.run(run_deployment(cfg))

    log.info(
        f"\n  {Colors.BOLD}Your app is live at:{Colors.RESET} "
        f"{Colors.CYAN}{result['compute']['endpoint']}{Colors.RESET}\n"
    )


@cli.command()
@click.option(
    "--port", "-p",
    default=8080,
    help="Port your application listens on (default: 8080).",
)
def init(port):
    """Initialize a new SoverGrid project in the current directory."""
    cwd = os.getcwd()
    project_name = os.path.basename(cwd)

    log.info(
        f"{Colors.BOLD}SoverGrid CLI v{__version__}{Colors.RESET}"
    )
    log.info(f"Initializing project '{project_name}'...\n")

    # Step 1: Generate sovergrid.yaml
    config_path = os.path.join(cwd, CONFIG_FILENAME)

    if os.path.exists(config_path):
        log.warning(
            f"{CONFIG_FILENAME} already exists. Skipping config generation."
        )
    else:
        config_content = DEFAULT_CONFIG.format(app_name=project_name)
        with open(config_path, "w") as f:
            f.write(config_content)
        log.info(
            f"{Colors.GREEN}Created {CONFIG_FILENAME}{Colors.RESET}"
        )

    # Step 2: Auto-detect project and generate Dockerfile
    project_type = detect_project_type(cwd)
    if project_type:
        generate_dockerfile(cwd, port=port)
    else:
        log.info(
            "No requirements.txt or package.json found.\n"
            "  A Dockerfile will be generated when you add one\n"
            "  and run 'sovergrid init' again."
        )

    # Step 3: Summary
    log.info(
        f"\n  {Colors.BOLD}{Colors.GREEN}"
        f"  Project initialized successfully.{Colors.RESET}\n\n"
        f"  Next steps:\n"
        f"  1. Review your {CONFIG_FILENAME}\n"
        f"  2. Run {Colors.CYAN}sovergrid deploy{Colors.RESET} "
        f"to deploy\n"
    )


@cli.command()
def status():
    """Check the status of your current deployment (mock)."""
    log.info(
        f"{Colors.BOLD}SoverGrid CLI v{__version__}{Colors.RESET}"
    )

    # In the real implementation, this will query the Akash API
    # for the status of the user's active deployments.
    log.info("Checking deployment status...\n")

    # Mock response
    log.info(
        f"  {Colors.GREEN}Status: ACTIVE{Colors.RESET}\n"
        f"  Provider: Akash Network\n"
        f"  Uptime: 99.97%\n"
        f"  Endpoint: https://akash-mock-123456.akash.network\n"
        f"  Monthly Cost: $0.62 (USDC)\n"
    )


@cli.command()
def info():
    """Display information about SoverGrid and the current config."""
    log.info(
        f"\n"
        f"  {Colors.BOLD}{Colors.MAGENTA}SoverGrid{Colors.RESET} "
        f"v{__version__}\n"
        f"  The one-click, un-censorable decentralized AWS.\n\n"
        f"  Supported Compute:  Akash, Spheron, Golem\n"
        f"  Supported Storage:  Filecoin, Arweave, IPFS\n"
        f"  Payment Tokens:     USDC, SVR\n"
        f"  License:            MIT\n"
    )

    # Try to load config if it exists
    config_path = os.path.join(os.getcwd(), CONFIG_FILENAME)
    if os.path.exists(config_path):
        cfg = SoverGridConfig.load(config_path)
        log.info(f"  Current project config:{cfg.summary()}")
    else:
        log.info(
            f"  No {CONFIG_FILENAME} in current directory.\n"
            f"  Run {Colors.CYAN}sovergrid init{Colors.RESET} to get started.\n"
        )


def main():
    """Entry point for the console script."""
    cli()


if __name__ == "__main__":
    main()
