"""
SoverGrid Auto-Dockerizer
Automatically detects the user's project type and generates
a production-ready Dockerfile.

This is Project 3.5: The Auto-Dockerizer (The Web2 to Web3 Bridge).
A Web2 developer types 'sovergrid init' and gets a Dockerfile
without ever learning Docker syntax.
"""

import os
from pathlib import Path

from sovergrid.logger import get_logger, Colors

log = get_logger(__name__)


# Dockerfile templates for each detected stack
TEMPLATES = {
    "python": {
        "detect_file": "requirements.txt",
        "name": "Python",
        "dockerfile": """\
# Auto-generated by SoverGrid CLI
# Stack: Python
# Optimized for deployment on decentralized compute (Akash, Spheron, Golem)

FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Install dependencies first (Docker layer caching)
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

# Expose the application port
EXPOSE {port}

# Run the application
CMD ["python", "app.py"]
""",
    },
    "python-fastapi": {
        "detect_file": "requirements.txt",
        "detect_content": "fastapi",
        "name": "Python (FastAPI)",
        "dockerfile": """\
# Auto-generated by SoverGrid CLI
# Stack: Python (FastAPI)
# Optimized for deployment on decentralized compute (Akash, Spheron, Golem)

FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE {port}

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "{port}"]
""",
    },
    "node": {
        "detect_file": "package.json",
        "name": "Node.js",
        "dockerfile": """\
# Auto-generated by SoverGrid CLI
# Stack: Node.js
# Optimized for deployment on decentralized compute (Akash, Spheron, Golem)

FROM node:20-alpine

WORKDIR /app

# Install dependencies first (Docker layer caching)
COPY package*.json ./
RUN npm ci --only=production

# Copy application code
COPY . .

EXPOSE {port}

CMD ["node", "index.js"]
""",
    },
    "node-nextjs": {
        "detect_file": "package.json",
        "detect_content": "next",
        "name": "Node.js (Next.js)",
        "dockerfile": """\
# Auto-generated by SoverGrid CLI
# Stack: Node.js (Next.js)
# Optimized for deployment on decentralized compute (Akash, Spheron, Golem)

# Stage 1: Build
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# Stage 2: Production
FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production

COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./

EXPOSE {port}

CMD ["npm", "start"]
""",
    },
}


def detect_project_type(project_dir: str) -> str:
    """
    Scans the project directory to detect the language and framework.
    Returns a key from the TEMPLATES dictionary.

    Detection order (most specific first):
    1. Check for Next.js (package.json containing 'next')
    2. Check for FastAPI (requirements.txt containing 'fastapi')
    3. Check for generic Node.js (package.json exists)
    4. Check for generic Python (requirements.txt exists)
    5. Return None if nothing is detected
    """
    project_path = Path(project_dir)

    # Check Node.js variants first
    package_json = project_path / "package.json"
    if package_json.exists():
        try:
            content = package_json.read_text()
            if '"next"' in content:
                return "node-nextjs"
        except (IOError, UnicodeDecodeError):
            pass
        return "node"

    # Check Python variants
    requirements = project_path / "requirements.txt"
    if requirements.exists():
        try:
            content = requirements.read_text().lower()
            if "fastapi" in content:
                return "python-fastapi"
        except (IOError, UnicodeDecodeError):
            pass
        return "python"

    return None


def generate_dockerfile(project_dir: str, port: int = 8080) -> str:
    """
    Detects the project type and generates a Dockerfile.
    Returns the path to the generated Dockerfile.

    Args:
        project_dir: Absolute path to the project root
        port: The port the application listens on (from sovergrid.yaml)
    """
    project_type = detect_project_type(project_dir)

    if project_type is None:
        log.warning(
            "Could not auto-detect your project type.\n"
            "  Make sure you have a 'requirements.txt' (Python) or\n"
            "  'package.json' (Node.js) in your project root.\n\n"
            "  You can also create a Dockerfile manually and set\n"
            "  'build.dockerfile' in your sovergrid.yaml."
        )
        return None

    template = TEMPLATES[project_type]
    stack_name = template["name"]

    log.info(f"Detected project type: {Colors.BOLD}{stack_name}{Colors.RESET}")

    # Generate the Dockerfile content with the correct port
    dockerfile_content = template["dockerfile"].format(port=port)

    # Write the Dockerfile
    dockerfile_path = os.path.join(project_dir, "Dockerfile")

    if os.path.exists(dockerfile_path):
        log.warning(
            "A Dockerfile already exists in this project.\n"
            "  Skipping generation to avoid overwriting your custom config.\n"
            "  Delete the existing Dockerfile and run 'sovergrid init' again\n"
            "  if you want SoverGrid to generate one for you."
        )
        return dockerfile_path

    with open(dockerfile_path, "w") as f:
        f.write(dockerfile_content)

    log.info(
        f"{Colors.GREEN}Dockerfile generated successfully.{Colors.RESET}\n"
        f"  Path: {dockerfile_path}\n"
        f"  Stack: {stack_name}\n"
        f"  Port: {port}"
    )

    return dockerfile_path
